language: ruby
cache: bundler

services:
  - docker

before_install:
  - bundle install

script:
  - bundle exec kitchen test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
